version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

commands:
  install:
    steps:
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-{{ checksum "yarn.lock" }}

jobs:
  main:
    executor: node
    parameters:
      publish:
        type: boolean
        default: false
    steps:
      - checkout
      - install
      - run:
          name: Lint
          command: |
            yarn tsc
            yarn lint --quiet
      - run:
          name: Test
          command: |
            yarn test --runInBand
            yarn codecov
      - run:
          name: Build
          command: yarn build
      - when:
          condition: << parameters.publish >>
          steps:
            - run:
                name: Login to NPM
                command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
            - run:
                name: Publish to NPM
                command: yarn lerna publish from-git --yes

workflows:
  version: 2
  ci:
    jobs:
      - main:
          name: build
          filters:
            tags:
              ignore: /.*/

      - main:
          name: publish
          publish: true
          context: npm-pkg
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
