name: Main

on:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.7.0
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1

      - run: yarn check:types
      - run: yarn lint
      - run: yarn test
      - uses: codecov/codecov-action@v1
      - run: yarn build

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1

      - run: yarn docs
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs

  e2e:
    needs:
      - checks
      - docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1
      - run: yarn cypress install
      - run: yarn percy exec -- cypress run
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          CYPRESS_HOST: https://ui.superdispatch.org
