name: PR

on: pull_request

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.7.0
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1
      - run: yarn check:types
      - run: yarn lint
      - run: yarn test
      - uses: codecov/codecov-action@v1

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1
      - uses: superdispatch/actions/build-size/limit@v1
        with:
          install_command: 'yarn install'
          build_command: 'yarn build'

  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1
      - run: yarn storybook:build
      - run: yarn playroom:build
      - uses: superdispatch/actions/deploy-preview@v1
        with:
          dir: docs
          netlify-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}

  e2e:
    needs:
      - checks
      - preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1
      - run: yarn cypress install
      - run: yarn percy exec -- cypress run
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          CYPRESS_HOST: https://preview-${{ github.event.number }}--ui-superdispatch.netlify.app
